### ISSUE TITLE
Full stack web developer 

### ISSUE THREAD

**Issue by GesJeremie** [skgtech/skg-startups-list#1]
[redacted for privacy reason]

**Comment by kbariotis** [comment]
Hey @GesJeremie,
great work you've putted there. Bravo! We should meet you in person. SKGTech is a team that organises meetups and other events very often. You should come on the next one either, schedule a coffee to meet you.

Regarding to your job search, are you interesting in startups located here in Thessaloniki? I may have some suggestions, not strictly from startups though cause there aren't so many here in Thessaloniki. But there are a few of them.

Cheers

**Comment by GesJeremie** [comment]
[redacted]

p.s. thanks for everything!

**Comment by kbariotis** [comment]
@GesJeremie You are welcome to join us at our slack team. I've sent you an invitation. Our conversations are mainly in Greek but feel free to say anything in English. We will respond! :)

There is also a Jobs channel at Slack where we constantly post about dev job open positions in Thessaloniki. I am sure you'll find it interested.

At the SKGtech site you will find all the tech related events that you can join and hopefully you'll find someone of us there. So don't be shy!

We will do a really fun, non tech, gathering really soon to drink some tsipouro. I'll send you more info once we close it.

So yeah, join us! :)
